---
- name: Remove GNOME software
  become: yes
  yum:
    # Asterisks at the end because of a bug in the underlying dnf module
    # https://github.com/ansible/ansible/issues/64294
    name:
      - gnome-maps*
      - gnome-abrt*
      - gnome-connections*
      - gnome-contacts*
      - gnome-tour*
      - gnome-boxes*
      - cheese
      - rhythmbox
    state: removed

- name: Delete home folders
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
  loop:
    - Public
    - Templates
